// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movies.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Movies.Domain.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("Movies.Domain.MovieAggregate.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("movie", (string)null);
                });

            modelBuilder.Entity("Movies.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("movie_cast", b =>
                {
                    b.Property<Guid>("movie_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("person_id")
                        .HasColumnType("uuid");

                    b.HasKey("movie_id", "person_id");

                    b.HasIndex("person_id");

                    b.ToTable("movie_cast");
                });

            modelBuilder.Entity("movie_director", b =>
                {
                    b.Property<Guid>("movie_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("person_id")
                        .HasColumnType("uuid");

                    b.HasKey("movie_id", "person_id");

                    b.HasIndex("person_id");

                    b.ToTable("movie_director");
                });

            modelBuilder.Entity("movie_genre", b =>
                {
                    b.Property<Guid>("movie_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("genre_id")
                        .HasColumnType("uuid");

                    b.HasKey("movie_id", "genre_id");

                    b.HasIndex("genre_id");

                    b.ToTable("movie_genre");
                });

            modelBuilder.Entity("movie_writer", b =>
                {
                    b.Property<Guid>("movie_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("person_id")
                        .HasColumnType("uuid");

                    b.HasKey("movie_id", "person_id");

                    b.HasIndex("person_id");

                    b.ToTable("movie_writer");
                });

            modelBuilder.Entity("Movies.Domain.Genre", b =>
                {
                    b.OwnsOne("Movies.Domain.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("GenreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.HasKey("GenreId");

                            b1.ToTable("genre");

                            b1.WithOwner()
                                .HasForeignKey("GenreId");
                        });

                    b.OwnsOne("Movies.Domain.GenreName", "Name", b1 =>
                        {
                            b1.Property<Guid>("GenreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("name");

                            b1.HasKey("GenreId");

                            b1.ToTable("genre");

                            b1.WithOwner()
                                .HasForeignKey("GenreId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Movies.Domain.MovieAggregate.Movie", b =>
                {
                    b.OwnsOne("Movies.Domain.AgeRestriction", "AgeRestriction", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varchar")
                                .HasColumnName("age_restriction");

                            b1.HasKey("MovieId");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("Movies.Domain.Duration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Minutes")
                                .HasColumnType("integer")
                                .HasColumnName("duration_minutes");

                            b1.HasKey("MovieId");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("Movies.Domain.Url", "BackdropUrl", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar")
                                .HasColumnName("backdrop_url");

                            b1.HasKey("MovieId");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("Movies.Domain.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.HasKey("MovieId");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("Movies.Domain.Url", "PosterUrl", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar")
                                .HasColumnName("poster_url");

                            b1.HasKey("MovieId");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("Movies.Domain.Url", "TrailerUrl", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar")
                                .HasColumnName("trailer_url");

                            b1.HasKey("MovieId");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("Movies.Domain.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<float>("AverageRating")
                                .HasColumnType("real")
                                .HasColumnName("average_rating");

                            b1.Property<int>("RatingCount")
                                .HasColumnType("integer")
                                .HasColumnName("rating_count");

                            b1.HasKey("MovieId");

                            b1.HasIndex("AverageRating")
                                .HasDatabaseName("IX_Movies_Rating");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("Movies.Domain.ReleaseDate", "ReleaseDate", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("release_date");

                            b1.HasKey("MovieId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_Movies_ReleaseDate");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("Movies.Domain.Tagline", "Tagline", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("varchar")
                                .HasColumnName("tagline");

                            b1.HasKey("MovieId");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("Movies.Domain.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("title");

                            b1.HasKey("MovieId");

                            b1.ToTable("movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.Navigation("AgeRestriction")
                        .IsRequired();

                    b.Navigation("BackdropUrl")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("PosterUrl")
                        .IsRequired();

                    b.Navigation("Rating")
                        .IsRequired();

                    b.Navigation("ReleaseDate")
                        .IsRequired();

                    b.Navigation("Tagline")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("TrailerUrl")
                        .IsRequired();
                });

            modelBuilder.Entity("Movies.Domain.Person", b =>
                {
                    b.OwnsOne("Movies.Domain.Biography", "Biography", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("biography");

                            b1.HasKey("PersonId");

                            b1.ToTable("person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Movies.Domain.BirthDate", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("Value")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.HasKey("PersonId");

                            b1.ToTable("person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Movies.Domain.Url", "PhotoUrl", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar")
                                .HasColumnName("photo_url");

                            b1.HasKey("PersonId");

                            b1.ToTable("person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Movies.Domain.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar")
                                .HasColumnName("name");

                            b1.HasKey("PersonId");

                            b1.ToTable("person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Biography")
                        .IsRequired();

                    b.Navigation("BirthDate")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PhotoUrl")
                        .IsRequired();
                });

            modelBuilder.Entity("movie_cast", b =>
                {
                    b.HasOne("Movies.Domain.MovieAggregate.Movie", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("movie_director", b =>
                {
                    b.HasOne("Movies.Domain.MovieAggregate.Movie", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("movie_genre", b =>
                {
                    b.HasOne("Movies.Domain.Genre", null)
                        .WithMany()
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Domain.MovieAggregate.Movie", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("movie_writer", b =>
                {
                    b.HasOne("Movies.Domain.MovieAggregate.Movie", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
